schema: workflow/2022.04
name: GetDepecheModeTracks
settings:
  error_notification: true
triggers:
- id: hi_ZbHvJ98
steps:
- namespace: get_artist_top_tracks
  runtime: nodejs18.x
  uses: spotify-get-artist-top-tracks@0.1.1
  props:
    spotify:
      authProvisionId: apn_3JhQwL
    artistId: 762310PdDnwsDxAQxzQkfX
    market: US
- namespace: filterResults
  runtime: nodejs18.x
  uses: "./filterResults/entry.js"
- namespace: returnJSON
  runtime: nodejs18.x
  uses: "./returnJSON/entry.js"

